### ISSUE TITLE
[Accessibility] Carousal

### ISSUE THREAD

**Issue by mkbansal1** [hlxsites/fonterra-fernleaf#110]
Report: https://pagespeed.web.dev/analysis/https-main--fonterra-fernleaf--hlxsites-hlx-live-en-products-milk-powder-for-whole-family/gak9bx7905?form_factor=mobile
Page: https://main--fonterra-fernleaf--hlxsites.hlx.live/en/products/milk-powder-for-whole-family

- [ ] "Explore our Product" wrong heading is used
<img width="885" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/fc237001-fd4b-44da-bbac-54eea776ae9d">

- [ ] Background & foreground color
<img width="905" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/362d42df-8735-4b41-ae3b-af868e339cab">

- [ ] Button name
<img width="921" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/afc3cd4d-6e0f-4641-82e3-69ea5419c38d">

- [ ] Serve images that are appropriately-sized
Note: We are using 1200px size image in url, which can be reduced to 400px
e.g https://main--fonterra-fernleaf--hlxsites.hlx.live/en/products/media_10849179472d8fb1243116089532bcd0d482421a8.png?width=350&format=pjpg&optimize=medium
<img width="915" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/c7be2a9d-0df1-43d8-bc01-d0fd2ba7f80e">

- [x] Images don't have height/width
<img width="888" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/2a25f262-0588-41e8-b7be-0a977a0d3906">

**Comment by ujjwal5** [comment]
One of the accessibility issue says "Background and foreground colors do not have a sufficient contrast ratio."
On checking the contrast of the used colors on [0], it is seen that these colors has a contrast ratio is 2:1 which is below standards (should be 4.5:1 for small text or 3:1 for large text). But since we want to keep same background and foreground colors as what is present on the customer website, we cannot fix this accessibility issue.

We can however inform customer that if they want get a score of 100 in accessibility they might have to re-evaluate the colour combination of headings in their website.

[0]: https://dequeuniversity.com/rules/axe/4.7/color-contrast

**Comment by ujjwal5** [comment]
- "Nutrition" wrong heading is used - this is being fixed by #157, changes on authoring side.
- Background & foreground color: need to update customer for the colour combination used.
- Button name: fix is on local.
- Images don't have height/width: already fixed in latest main branch.
- Serve images that are appropriately-sized: pending currently working on this.

**Comment by ujjwal5** [comment]
@asthabh23 As discussed over the slack channel, if we use the foreground colour as what is present on live site, we will not be able to fix the accessibility issue. 
As @sselvara mentioned, that the closest colour which will fix this issue is #663300 but then the product page will look something like below. If client is fine with this, we can go ahead and update the colour.

<img width="1385" alt="Screenshot 2023-08-18 at 7 25 19 PM" src="https://github.com/hlxsites/fonterra-fernleaf/assets/7971922/252a8a94-2986-4838-a9cb-79d26a63021a">


P.S: We might need to change from yellow to this colour to maintain parity in the website as a whole.

**Comment by asthabh23** [comment]
@ujjwal5 I get this!
Please let me know what all pages will have this change to fix the accessibility fixed across?
I will share the status with the customer as info to let them know beforehand.
