### ISSUE TITLE
[Hero Block with milk splash images] Product and Recipe Pages

### ISSUE THREAD

**Issue by asthabh23** [hlxsites/fonterra-fernleaf#60]
Example URL: https://www.fernleaf.com.my/en/products/protein-plus-milk-powder.html

[Authoring] The better way to author the 3 images:
- a banner image in the background
- a milk splash image over it
- product image in the center over the top.

would be to add the milk splash image also in the hero block (to give flexibility of changing image to author anytime at a later point)

The images can then be managed using z-index property in CSS. Just ordering the images in layers from z-index -1, 0, +1

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara , this needs to be updated at authoring level.
The picture can be used directly from doc instead of using background image url at code level

**Comment by sselvara** [comment]
> @mkbansal1 @sselvara , this needs to be updated at authoring level. The picture can be used directly from doc instead of using background image url at code level

@noormd08 FYI.

**Comment by mkbansal1** [comment]
I am discussing this approach with @asthabh23 

I will update the card with final approach.

**Comment by mkbansal1** [comment]
@asthabh23 
The approach you have recommended to allow editors to configure 2 additional splash images (desktop & mobile) per hero banner will definitely provide flexibility to editors to manage splash images and allow them to change images if they need to, but this approach has some challenges:
- Editors need to configure two additional images per product/recipe, though the splash image is common for all products and recipes, so it will be an authoring overhead.
- If the splash image needs to be changed, editors need to change images on all products / recipe, which will be authoring overhead and does not provide a better authoring experience.

I recommend the following approach instead:
1. If we want the flexibility to allow editors to manage splash images, we can create an image folder in SharePoint and use the naming pattern to have different splash images.
We will update our code to point to splash images from SharePoint instead of GitHub image folder.
2. Alternatively, we can follow the current approach but use hero variation (small-splash / big-splash) to define splash image.

Please let me know if you are aligned with any of the above two approaches or we can discuss it further.

@sselvara

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara 
To better deal with this and considering better author experience, I would recommend considering fragment approach.
Approach: Create two fragment docs (one for Recipe and one for Product) and add link to those fragments in the hero block to be handled. So this way we would have only one place to add/update the splash image and that can be pulled into the respective pages.

**Comment by asthabh23** [comment]
@mkbansal1 , as per the inputs we have received around the discussion on this:
- The fragment approach can be considered if customer says that they would need control of the watermark image to change it at a later point (let's park this approach for now)
- Meanwhile, let's proceed with what rofe has mentioned as a solution: considering to _not_ put images in GH, rather adding them in sharepoint.

**Comment by mkbansal1** [comment]
@asthabh23 Please try to get a response from the client, team is occupied with other activities, so we can wait on this for some days.

**Comment by asthabh23** [comment]
Customer has confirmed to have the milk splash image authorable, so the first approach can be considered for implementation.

**Comment by nishant-gupta** [comment]
Since we need authoring capability for the splash image, it is also imperative to make the authoring experience simple and intuitive. authoring on each page would be unnecessary overkill. Similarly a fragment approach would be a bit too complex specially considering the use case. 

The requirement is simple - 
- allow authors to upload 4 images (product + recipe / mobile + desktop)
- allow authors to specify somewhere that these should be used for respective cases

We can rather leverage placeholders where the authors can easily in a single place specify the 4 images after uploading them via SharePoint or Slackbot. we already leverage the placeholders for various reasons and hence loading these would be straight forward. rest can be seamlessly managed via code.

In future as long as the authors want to just change the images they can upload new ones and update placeholders excel. for anything more a bigger redesign may anyways be needed.

**Comment by mkbansal1** [comment]
On top of @nishant-gupta approach, there are a few more images, which need to be used by the above approach

- Story n Tips listing page (Top bg & bottom bg / Desktop + Mobile)
- Story n Tips landing page (Top bg & bottom bg / Desktop + Mobile)
<img width="1721" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/626f9a4c-8553-4ba9-8ec3-22afa688d579">

**Comment by asthabh23** [comment]
@nishant-gupta @mkbansal1 
analysing all approaches, the best approach to proceed with right now would be the placeholders one. Basically adding milk-splash image as a placeholder. 
Its just that since customer has mentioned that there is a possibility that the image may not be part of the brand guidelines in the future, so let's make our code resilient enough to adapt to that scenario when image is not present in the placeholder (handling null or empty case).

Let's proceed with this approach.

**Comment by asthabh23** [comment]
also, @mkbansal1 while we proceed with this approach, let's make sure to remove the unrequired images from GH repo as an after step (once those are moved to Sharepoint)

**Comment by sselvara** [comment]
@ParthasharathiB  FYI

> also, @mkbansal1 while we proceed with this approach, let's make sure to remove the unrequired images from GH repo as an after step (once those are moved to Sharepoint)

**Comment by asthabh23** [comment]
@mkbansal1 @sselvara 
Based on discussion, we will proceed with placement of splash image as below:
- Place product splash image (that we see on product pages) when we have bg-image, product-image and splash image to be placed in hero block (3 images altogether)

- for the rest of recipe/product pages, have the recipe page specific milk splash image added.

**Comment by sselvara** [comment]
> @mkbansal1 @sselvara Based on discussion, we will proceed with placement of splash image as below:
> 
> * Place product splash image (that we see on product pages) when we have bg-image, product-image and splash image to be placed in hero block (3 images altogether)
> * for the rest of recipe/product pages, have the recipe page specific milk splash image added.

@ParthasharathiB FYI
